[project]
name = "scratch2scale-wip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "huggingface-hub[cli]>=0.35.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
